<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_reg.pbru.ac.th  register</name>
   <tag></tag>
   <elementGuidId>c1d391f6-20fc-433a-8bba-86537c7034c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c78c820b-8f0c-4ffe-b9ab-7043119013ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p</value>
      <webElementGuid>b8918e5b-94c3-4a0d-9cee-83d69aa5662b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-matarget</name>
      <type>Main</type>
      <value>algo</value>
      <webElementGuid>165e92f3-5863-41b9-975f-39c25276faba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://reg.pbru.ac.th/register/</value>
      <webElementGuid>4e8a243f-a055-488c-bfa4-2b91fca75526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>b049edd7-5e39-4bd5-9a1a-6ad23bf5266d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>5ef085b0-678a-4f69-a27f-fd443a912fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-88d</name>
      <type>Main</type>
      <value>65a63c2137d49</value>
      <webElementGuid>2c75362a-71d3-4b59-bc03-463eb5dd290b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>ระบบบริการการศึกษา มหาวิทยาลัยราชภัฏเพชรบุรี</value>
      <webElementGuid>420ad940-98bc-4cd3-8f53-441c4dd2d312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>reg.pbru.ac.th › registerระบบบริการการศึกษา มหาวิทยาลัยราชภัฏเพชรบุรี</value>
      <webElementGuid>58e5f55e-ec5a-4242-862a-a6fc60ebb701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;web&quot;)/ol[@class=&quot;reg searchCenterMiddle&quot;]/li[@class=&quot;first&quot;]/div[@class=&quot;dd algo algo-sr relsrch fst Sr&quot;]/div[@class=&quot;compTitle options-toggle&quot;]/h3[@class=&quot;title&quot;]/a[@class=&quot;d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p&quot;]</value>
      <webElementGuid>b6f6ea50-ace3-4ee2-ac6f-f47aea6af424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      <webElementGuid>e37c896e-e3bc-49b8-822d-936678fb3612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://reg.pbru.ac.th/register/')]</value>
      <webElementGuid>490bc7af-6988-49f5-a49b-e6e2063d660c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>c8719353-750d-4bba-ba67-a2bc847f6f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://reg.pbru.ac.th/register/' and (text() = 'reg.pbru.ac.th › registerระบบบริการการศึกษา มหาวิทยาลัยราชภัฏเพชรบุรี' or . = 'reg.pbru.ac.th › registerระบบบริการการศึกษา มหาวิทยาลัยราชภัฏเพชรบุรี')]</value>
      <webElementGuid>d96c854f-e707-44fb-912f-13da6bf0c8da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
