<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonybar-search</name>
   <tag></tag>
   <elementGuidId>0f858520-cf7d-4248-a8d9-507e9f95ccf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ybar-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ybar-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42b9b34d-ebd0-45ed-92b1-e917f8ee2b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>57aa046a-82a7-4d6e-a8bb-409c8c44b7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ybar-search</value>
      <webElementGuid>dbd765cb-ae67-46a9-ae79-31c8939e94ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rapid-noclick-resp _yb_1fy0v </value>
      <webElementGuid>c252e714-0fcc-4a61-8ff6-eeb143e86580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>76959d1e-d689-4b6e-adcd-d1b00119ea58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>72f275be-fb4c-4802-8cdb-dac103d47b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ylk</name>
      <type>Main</type>
      <value>slk:websrch;elm:search;elmt:icon;sec:ybar;subsec:searchbox;itc:0;tar:search.yahoo.com;</value>
      <webElementGuid>1af3a854-6327-4f43-97f8-9cc7a21c47a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rapid_p</name>
      <type>Main</type>
      <value>257</value>
      <webElementGuid>b22a1ef7-d8b8-47e3-a117-4e49edda60a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-v9y</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9015eccd-2f95-4ff9-943b-51bc3dfa351d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ybar-search&quot;)</value>
      <webElementGuid>eff12fa2-6309-4c87-a858-885bdd187e2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ybar-search']</value>
      <webElementGuid>eb71b2eb-a350-4348-a400-af006e36e521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ybar-sf']/div[4]/button</value>
      <webElementGuid>8b538957-60c2-4b9d-bf65-e9c5a051752a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>4705fb43-09f4-49db-b4d3-b75c3bf3d078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'ybar-search']</value>
      <webElementGuid>a52d179e-a87e-4427-933a-bec945381078</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
